routes/web.php
<?php
Route::redirect('/', 'admin/home');

Auth::routes(['register' => false]);

// Change Password Routes...
Route::get('change_password', 'Auth\ChangePasswordController@showChangePasswordForm')->name('auth.change_password');
Route::patch('change_password', 'Auth\ChangePasswordController@changePassword')->name('auth.change_password');

Route::group(['middleware' => ['auth'], 'prefix' => 'admin', 'as' => 'admin.'], function () {
    Route::get('/home', 'HomeController@index')->name('home');
    Route::resource('permissions', 'Admin\PermissionsController');
    Route::delete('permissions_mass_destroy', 'Admin\PermissionsController@massDestroy')->name('permissions.mass_destroy');
    Route::resource('roles', 'Admin\RolesController');
    Route::delete('roles_mass_destroy', 'Admin\RolesController@massDestroy')->name('roles.mass_destroy');
    Route::resource('users', 'Admin\UsersController');
    Route::delete('users_mass_destroy', 'Admin\UsersController@massDestroy')->name('users.mass_destroy');
    Route::resource('events', 'Admin\EventController');
    Route::delete('event/delete', 'Admin\EventController@deleteAjax')->name('event.delete');

});

app/Event.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Event extends Model
{
    use HasFactory;
    protected $fillable = ['title', 'description', 'start_date', 'end_date', 'display', 'created_by'];

}

app/Http/Controllers/Admin/EventController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Event;
use App\Http\Controllers\Controller;
use Auth;
use Carbon\carbon;
use Illuminate\Http\Request;

class EventController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        $currentDate = Carbon::now();
        if ($request->search == "finish_event") {
            
            $events = Event::where('end_date', '<', $currentDate)->orderBy('end_date', 'asc')->paginate(10);
        }elseif ($request->search == "upcoming_event") {
            $events = Event::where('start_date', '>=', $currentDate)->orderBy('start_date', 'asc')->paginate(10);
        } else {
            $events = Event::orderBy('start_date', 'asc')->paginate(10);
        }

        return view('admin.event.index', compact('events'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('admin.event.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $this->validate($request, [
            'title' => 'required|string|max:250',
            'description' => 'required|string|max:1000',
            'start_date' => 'required|date',
            'end_date' => 'required|date',
            'display' => 'nullable|boolean',
        ]);
        $event = new Event;
        $event->title = $request->title;
        $event->description = $request->description;
        $event->start_date = $request->start_date;
        $event->end_date = $request->end_date;
        $event->display = $request->display ?? 0;
        $event->created_by = Auth::user()->name;
        $status = $event->save();
        if ($status) {
            return redirect()->route('admin.events.index')->with('status', 'Successfully Creted!');
        }
        return redirect()->route('admin.events.index')->with('error', 'Something error!');

    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Event  $event
     * @return \Illuminate\Http\Response
     */
    public function show(Event $event)
    {
        return view('admin.event.show', compact('event'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Event  $event
     * @return \Illuminate\Http\Response
     */
    public function edit(Event $event)
    {
        return view('admin.event.edit', compact('event'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Event  $event
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Event $event)
    {
        // return $event;
        $this->validate($request, [
            'title' => 'required|string|max:250',
            'description' => 'required|string|max:1000',
            'start_date' => 'required|date',
            'end_date' => 'required|date',
            'display' => 'nullable|boolean',
        ]);
        $event->title = $request->title;
        $event->description = $request->description;
        $event->start_date = $request->start_date;
        $event->end_date = $request->end_date;
        $event->display = $request->display ?? 0;
        $event->created_by = Auth::user()->name;
        $status = $event->update();
        if ($status) {
            return redirect()->route('admin.events.index')->with('status', 'Successfully Updated!');
        }
        return redirect()->route('admin.events.index')->with('error', 'Something error!');

    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Event  $event
     * @return \Illuminate\Http\Response
     */
    public function deleteAjax(Request $request)
    {
        // return $request;
        $event = Event::findOrFail($request->id);
        $event->delete();
        return response()->json([
            'success' => 'Event deleted successfully!',
        ]);
    }
}

resources/views/admin/event/create.blade.php
@extends('layouts.admin')
@section('content')
    <div class="card">
        <div class="card-header">
            User Add
        </div>

        <div class="card-body">
            <form action="{{ route('admin.events.store') }}" method="POST" enctype="multipart/form-data">
                @csrf
                <div class="form-group {{ $errors->has('title') ? 'has-error' : '' }}">
                    <label for="title">Title *</label>
                    <input type="text" id="title" name="title" class="form-control"
                        value="{{ old('title', isset($event) ? $event->title : '') }}" required>
                    @if ($errors->has('title'))
                        <em class="invalid-feedback">
                            {{ $errors->first('title') }}
                        </em>
                    @endif

                </div>
                <div class="form-group {{ $errors->has('start_date') ? 'has-error' : '' }}">
                    <label for="start_date">Start Date *</label>
                    <input type="date" id="start_date" name="start_date" class="form-control"
                        value="{{ old('start_date', isset($event) ? $event->start_date : '') }}" required>
                    @if ($errors->has('start_date'))
                        <em class="invalid-feedback">
                            {{ $errors->first('start_date') }}
                        </em>
                    @endif

                </div>
                <div class="form-group {{ $errors->has('end_date') ? 'has-error' : '' }}">
                    <label for="end_date">End Date *</label>
                    <input type="date" id="end_date" name="end_date" class="form-control"
                        value="{{ old('end_date', isset($event) ? $event->end_date : '') }}" required>
                    @if ($errors->has('end_date'))
                        <em class="invalid-feedback">
                            {{ $errors->first('end_date') }}
                        </em>
                    @endif

                </div>

                <div class="form-group {{ $errors->has('display') ? 'has-error' : '' }}">
                    <label for="display">Display *
                        <input type="checkbox" name="display"
                            value="1"{{ old('dispaly', isset($event) ? $event->display : '') == 1 ? 'checked' : '' }}>

                        @if ($errors->has('display'))
                            <em class="invalid-feedback">
                                {{ $errors->first('display') }}
                            </em>
                        @endif

                </div>
                <div class="form-group {{ $errors->has('description') ? 'has-error' : '' }}">
                    <label for="description">Description *</label>
                    <textarea id="description" name="description" class="form-control">{{ old('description', isset($event) ? $event->description : '') }}</textarea>
                    @if ($errors->has('description'))
                        <em class="invalid-feedback">
                            {{ $errors->first('description') }}
                        </em>
                    @endif

                </div>
                <div>
                    <input class="btn btn-primary" type="submit" value="{{ trans('global.save') }}">
                </div>
            </form>


        </div>
    </div>
@endsection

resources/views/admin/event/edit.blade.php
@extends('layouts.admin')
@section('content')
    <div class="card">
        <div class="card-header">
            Event Edit
        </div>

        <div class="card-body">
            <form action="{{ route('admin.events.update', [$event->id]) }}" method="POST" enctype="multipart/form-data">
                @csrf
                @method('PUT')
                <div class="form-group {{ $errors->has('title') ? 'has-error' : '' }}">
                    <label for="title">Title *</label>
                    <input type="text" id="title" name="title" class="form-control"
                        value="{{ old('title', isset($event) ? $event->title : '') }}" required>
                    @if ($errors->has('title'))
                        <em class="invalid-feedback">
                            {{ $errors->first('title') }}
                        </em>
                    @endif

                </div>
                <div class="form-group {{ $errors->has('start_date') ? 'has-error' : '' }}">
                    <label for="start_date">Start Date *</label>
                    <input type="date" id="start_date" name="start_date" class="form-control"
                        value="{{ old('start_date', isset($event) ? $event->start_date : '') }}" required>
                    @if ($errors->has('start_date'))
                        <em class="invalid-feedback">
                            {{ $errors->first('start_date') }}
                        </em>
                    @endif

                </div>
                <div class="form-group {{ $errors->has('end_date') ? 'has-error' : '' }}">
                    <label for="end_date">End Date *</label>
                    <input type="date" id="end_date" name="end_date" class="form-control"
                        value="{{ old('end_date', isset($event) ? $event->end_date : '') }}" required>
                    @if ($errors->has('end_date'))
                        <em class="invalid-feedback">
                            {{ $errors->first('end_date') }}
                        </em>
                    @endif

                </div>

                <div class="form-group {{ $errors->has('display') ? 'has-error' : '' }}">
                    <label for="display">Display *
                        <input type="checkbox" name="display"
                            value="1"{{ old('dispaly', isset($event) ? $event->display : '') == 1 ? 'checked' : '' }}>

                        @if ($errors->has('display'))
                            <em class="invalid-feedback">
                                {{ $errors->first('display') }}
                            </em>
                        @endif

                </div>
                <div class="form-group {{ $errors->has('description') ? 'has-error' : '' }}">
                    <label for="description">Description *</label>
                    <textarea id="description" name="description" class="form-control">{{ old('description', isset($event) ? $event->description : '') }}</textarea>
                    @if ($errors->has('description'))
                        <em class="invalid-feedback">
                            {{ $errors->first('description') }}
                        </em>
                    @endif

                </div>
                <div>
                    <input class="btn btn-danger" type="submit" value="{{ trans('global.save') }}">
                </div>
            </form>


        </div>
    </div>
@endsection

resources/views/admin/event/index.blade.php
@extends('layouts.admin')
@section('content')
    @can('events_manage')
        <div style="margin-bottom: 10px;" class="row">
            <div class="col-lg-12">
                <a class="btn btn-success" href="{{ route('admin.events.create') }}">
                    Add Event
                </a>

                <a class="btn btn-primary" href="{{ route('admin.events.index',['search'=>'finish_event']) }}">
                    Finined Event
                </a>
                <a class="btn btn-info" href="{{ route('admin.events.index',['search'=>'upcoming_event']) }}">
                    Upcoming Event
                </a>
            </div>
        </div>
    @endcan
    <div class="card">
        <div class="card-header">
            Event Lists
        </div>

        <div class="card-body">
            <div class="table-responsive">
                <table class=" table table-bordered table-striped table-hover datatable datatable-event">
                    <thead>
                        <tr>
                            <th>
                                S.N
                            </th>
                            <th>
                                Title
                            </th>
                            <th>
                                Start Date
                            </th>
                            <th>
                                End Date
                            </th>
                            <th>
                                Display
                            </th>
                            <th>
                                Action
                            </th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach ($events as $key => $event)
                            <tr>
                                <td>
                                    {{ $key + 1 }}
                                </td>
                                <td>
                                    {{ $event->title ?? '' }}
                                </td>
                                <td>
                                    {{ $event->start_date ?? '' }}
                                </td>
                                <td>
                                    {{ $event->end_date ?? '' }}
                                </td>
                                <td>
                                    @if ($event->display == 1)
                                        <span class="badge badge-success">Displayed</span>
                                    @else
                                        <span class="badge badge-danger">Non-Displayed</span>
                                    @endif
                                </td>
                                <td>
                                    <a class="btn btn-xs btn-primary" href="{{ route('admin.events.show', $event->id) }}">
                                        {{ trans('global.view') }}
                                    </a>

                                    <a class="btn btn-xs btn-info" href="{{ route('admin.events.edit', $event->id) }}">
                                        {{ trans('global.edit') }}
                                    </a>
                                    <button class="deleteEvent btn btn-xs btn-danger" data-id="{{ $event->id }}"
                                        data-token="{{ csrf_token() }}">Delete</button>
                                </td>

                            </tr>
                        @endforeach
                    </tbody>
                </table>
            </div>


        </div>
    </div>
@endsection
@section('scripts')
    <script>
        $(".deleteEvent").click(function() {
            var id = $(this).data("id");
            // alert(id);
            var token = $(this).data("token");
            confirm('Are you sure you want to delete this item')
            $.ajax({
                url: "{{ route('admin.event.delete') }}",
                type: 'DELETE',
                data: {
                    "id": id,
                    "_token": token,
                },
                success: function(response) {
                    alert(response['success']);
                }

            });

        });
    </script>
@endsection

resources/views/admin/event/show.blade.php
@extends('layouts.admin')
@section('content')
    <div class="card">
        <div class="card-header">
             Show Event
        </div>

        <div class="card-body">
            <div class="mb-2">
                <table class="table table-bordered table-striped">
                    <tbody>

                        <tr>
                            <th>
                                Title
                            </th>
                            <td>
                                {{ $event->title ?? '' }}
                            </td>
                        </tr>
                        <tr>
                            <th>
                                Start Date
                            </th>
                            <td>
                                {{ $event->start_date ?? '' }}
                            </td>
                        </tr>
                        <tr>
                            <th>
                                End Date
                            </th>
                            <td>
                                {{ $event->end_date ?? '' }}
                            </td>
                        </tr>
                       
                        <tr>
                            <th>
                                Display
                            </th>
                            <td>
                                 @if ($event->display==1)
                                        <span class="badge badge-success">Displayed</span>
                                        @else
                                        <span class="badge badge-danger">Non-Displayed</span>

                                    @endif
                            </td>
                        </tr>
                         <tr>
                            <th>
                                Description
                            </th>
                            <td>
                                <p>{{ $event->description ?? '' }}</p>
                            </td>
                        </tr>
                    </tbody>
                </table>
                <a style="margin-top:20px;" class="btn btn-default" href="{{ url()->previous() }}">
                    {{ trans('global.back_to_list') }}
                </a>
            </div>


        </div>
    </div>
@endsection